name: Build and deploy .NET Core app to Windows WebApp MassCalculator
on:
  push:
    branches:
    - main
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: MassCalculator
  AZURE_WEBAPP_PACKAGE_PATH: MassCalculator/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.MassCalculator_e026 }}
  CONFIGURATION: Release
  WORKING_DIRECTORY: MassCalculator
  
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: dotnet test "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }}
    - run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
    - uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
